/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MChar230glereRouteImport } from './routes/mæglere'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BoligerRouteImport } from './routes/boliger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoligIdRouteImport } from './routes/bolig.$id'

const MChar230glereRoute = MChar230glereRouteImport.update({
  id: '/mæglere',
  path: '/mæglere',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BoligerRoute = BoligerRouteImport.update({
  id: '/boliger',
  path: '/boliger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoligIdRoute = BoligIdRouteImport.update({
  id: '/bolig/$id',
  path: '/bolig/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/favorites': typeof FavoritesRoute
  '/mæglere': typeof MChar230glereRoute
  '/bolig/$id': typeof BoligIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/favorites': typeof FavoritesRoute
  '/mæglere': typeof MChar230glereRoute
  '/bolig/$id': typeof BoligIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/favorites': typeof FavoritesRoute
  '/mæglere': typeof MChar230glereRoute
  '/bolig/$id': typeof BoligIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boliger' | '/favorites' | '/mæglere' | '/bolig/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boliger' | '/favorites' | '/mæglere' | '/bolig/$id'
  id: '__root__' | '/' | '/boliger' | '/favorites' | '/mæglere' | '/bolig/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoligerRoute: typeof BoligerRoute
  FavoritesRoute: typeof FavoritesRoute
  MChar230glereRoute: typeof MChar230glereRoute
  BoligIdRoute: typeof BoligIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mæglere': {
      id: '/mæglere'
      path: '/mæglere'
      fullPath: '/mæglere'
      preLoaderRoute: typeof MChar230glereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boliger': {
      id: '/boliger'
      path: '/boliger'
      fullPath: '/boliger'
      preLoaderRoute: typeof BoligerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolig/$id': {
      id: '/bolig/$id'
      path: '/bolig/$id'
      fullPath: '/bolig/$id'
      preLoaderRoute: typeof BoligIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoligerRoute: BoligerRoute,
  FavoritesRoute: FavoritesRoute,
  MChar230glereRoute: MChar230glereRoute,
  BoligIdRoute: BoligIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
