/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoligerRouteImport } from './routes/boliger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MChar230glereIndexRouteImport } from './routes/mæglere/index'
import { Route as MChar230glereIdRouteImport } from './routes/mæglere/$id'
import { Route as BoligIdRouteImport } from './routes/bolig.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoligerRoute = BoligerRouteImport.update({
  id: '/boliger',
  path: '/boliger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MChar230glereIndexRoute = MChar230glereIndexRouteImport.update({
  id: '/mæglere/',
  path: '/mæglere/',
  getParentRoute: () => rootRouteImport,
} as any)
const MChar230glereIdRoute = MChar230glereIdRouteImport.update({
  id: '/mæglere/$id',
  path: '/mæglere/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoligIdRoute = BoligIdRouteImport.update({
  id: '/bolig/$id',
  path: '/bolig/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bolig/$id': typeof BoligIdRoute
  '/mæglere/$id': typeof MChar230glereIdRoute
  '/mæglere/': typeof MChar230glereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bolig/$id': typeof BoligIdRoute
  '/mæglere/$id': typeof MChar230glereIdRoute
  '/mæglere': typeof MChar230glereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boliger': typeof BoligerRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bolig/$id': typeof BoligIdRoute
  '/mæglere/$id': typeof MChar230glereIdRoute
  '/mæglere/': typeof MChar230glereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boliger'
    | '/contact'
    | '/favorites'
    | '/auth/login'
    | '/auth/register'
    | '/bolig/$id'
    | '/mæglere/$id'
    | '/mæglere/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boliger'
    | '/contact'
    | '/favorites'
    | '/auth/login'
    | '/auth/register'
    | '/bolig/$id'
    | '/mæglere/$id'
    | '/mæglere'
  id:
    | '__root__'
    | '/'
    | '/boliger'
    | '/contact'
    | '/favorites'
    | '/auth/login'
    | '/auth/register'
    | '/bolig/$id'
    | '/mæglere/$id'
    | '/mæglere/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoligerRoute: typeof BoligerRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BoligIdRoute: typeof BoligIdRoute
  MChar230glereIdRoute: typeof MChar230glereIdRoute
  MChar230glereIndexRoute: typeof MChar230glereIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boliger': {
      id: '/boliger'
      path: '/boliger'
      fullPath: '/boliger'
      preLoaderRoute: typeof BoligerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mæglere/': {
      id: '/mæglere/'
      path: '/mæglere'
      fullPath: '/mæglere/'
      preLoaderRoute: typeof MChar230glereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mæglere/$id': {
      id: '/mæglere/$id'
      path: '/mæglere/$id'
      fullPath: '/mæglere/$id'
      preLoaderRoute: typeof MChar230glereIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolig/$id': {
      id: '/bolig/$id'
      path: '/bolig/$id'
      fullPath: '/bolig/$id'
      preLoaderRoute: typeof BoligIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoligerRoute: BoligerRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BoligIdRoute: BoligIdRoute,
  MChar230glereIdRoute: MChar230glereIdRoute,
  MChar230glereIndexRoute: MChar230glereIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
